### REGISTER USER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "myusername",
    "password": "pass1234"
}

### LOGIN USER
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "myusername",
    "password": "pass1234"
}


### GET /game/genre/2
GET http://localhost:5000/game/genre/2


### GET /game/id/57016   (sinjid: battle arena)
GET http://localhost:5000/game/id/57016

### GET /game/search?q="zelda"
GET http://localhost:5000/game/search?q=zelda
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2MzExODE0LCJleHAiOjE3NDYzOTgyMTR9.q1qLhW1hQiuIjabd_t0ki4_URVen1jSxeYIWZkR3ji4

### POST /reviews/
POST http://localhost:5000/reviews/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2MzEzMDE3LCJleHAiOjE3NDYzOTk0MTd9.H5hfR-S7ml9iEJaQIoQWlKn2DEVifAC0S89EU4192P8
Content-Type: application/json

{
    "rating": 2,
    "review": "great game",
    "game_id": 57016
}

### GET /reviews/rating/57016
GET http://localhost:5000/reviews/rating/57016
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2MzEyNjAwLCJleHAiOjE3NDYzOTkwMDB9.vPd9Jga64CD6nIMUM_95WmEW8iFjm8JgFXyYdCjYXtc

### GET /reviews/
GET http://localhost:5000/reviews/57016
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2MzEyNjAwLCJleHAiOjE3NDYzOTkwMDB9.vPd9Jga64CD6nIMUM_95WmEW8iFjm8JgFXyYdCjYXtc


### UPDATE /reviews/1
PUT http://localhost:5000/reviews/1
Content-Type: application/json

{
    "rating": 1,
    "review": "bad game"
}

### DELETE /reviews/1
DELETE http://localhost:5000/reviews/1

### GET / 
GET http://localhost:5000/game/genre/2

