### REGISTER USER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "myusername",
    "password": "pass1234"
}

### LOGIN USER
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "user",
    "password": "pass"
}


### GET /game/genre/2
GET http://localhost:5000/game/genre/2


### GET /game/id/57016   (sinjid: battle arena)
GET http://localhost:5000/game/id/57016

### GET /game/search?q="zelda"
GET http://localhost:5000/game/search?q=zelda
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2MzExODE0LCJleHAiOjE3NDYzOTgyMTR9.q1qLhW1hQiuIjabd_t0ki4_URVen1jSxeYIWZkR3ji4

### POST /reviews/
POST http://localhost:5000/reviews/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQ2NTQ5NTYzLCJleHAiOjE3NDY2MzU5NjN9.JTGZqzK-AZ1Bf3M3DgUKAd6GM7z9GiQjKGdrbK8YXE4
Content-Type: application/json

{
    "rating": 2,
    "review": "great game",
    "game_id": 57016
}

### GET /reviews/rating/57016
GET http://localhost:5000/reviews/rating/57016
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTQ4MjQ0LCJleHAiOjE3NDY2MzQ2NDR9._RlkuoG2v-q9kPuQQNAKqpcD8cnX7kD7_mnBZZFhUAw

### GET /reviews/
GET http://localhost:5000/reviews/57016
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTQ4MTY3LCJleHAiOjE3NDY2MzQ1Njd9.ks7lE-pqfwKj9LfOMlNq4htDlQk90MonXsjAqBbvazc

### GET /reviews/mine/57016
GET http://localhost:5000/reviews/mine/57016
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ2NTQ4MTY3LCJleHAiOjE3NDY2MzQ1Njd9.ks7lE-pqfwKj9LfOMlNq4htDlQk90MonXsjAqBbvazc


### UPDATE /reviews/1
PUT http://localhost:5000/reviews/1
Content-Type: application/json

{
    "rating": 1,
    "review": "bad game"
}

### DELETE /reviews/1
DELETE http://localhost:5000/reviews/1

### GET / 
GET http://localhost:5000/game/genre/2

